root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main.exe"
  cmd = "templ generate . && go build -o ./tmp/main.exe cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = [".*_templ.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html"]
  kill_delay = "0s"
  # Poll files for changes instead of using fsnotify.
  # poll = true
  # Poll interval (defaults to the minimum interval of 500ms).
  # poll_interval = 500 # ms
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "grey"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false