version: "3.3"
services:
  web:
    environment: 
      - TZ=Asia/Kolkata
    build: 
      context: ./dashboard
      dockerfile: prod.dockerfile
    image: h20180061/dashboard:${WEB_TAG}
    ports:
      - "80:80"
    container_name: web
    depends_on:
      - app
    networks:
        - network1

  app:
    environment: 
      - TZ=Asia/Kolkata
    build: 
      context: ./app
      dockerfile: Dockerfile
    image: h20180061/trends:${APP_TAG}
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./app/data:/home/app/data
    networks:
        - network1

networks:
  network1: