version: "3.3"
services:
  web:
    environment:
      - TZ=Asia/Kolkata
      - API_URL=127.0.0.1
    build:
      context: ./dashboard
      dockerfile: prod.dockerfile
    image: h20180061/dashboard:${WEB_TAG}
    ports:
      - "80:80"
    container_name: web
    depends_on:
      - app
    volumes:
      - ./data:/home/app/data
    networks:
      - network1

  app:
    environment:
      - TZ=Asia/Kolkata
    build:
      context: golang
      dockerfile: Dockerfile
    image: h20180061/trends:${APP_TAG}
    ports:
      - "5000:5000"
      - "5001:5001"
    container_name: app
    volumes:
      - ./golang/data:/home/app/data
    networks:
      - network1

networks:
  network1: null
