version: "3.3"
services:
  app:
    environment:
      - TZ=Asia/Kolkata
    image: h20180061/trends:1.0
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./data:/home/app/data
