version: "3.3"
services:
  trends:
    ports:
      - "5001:5001"
    container_name: trends
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data:/app/data
