services:
  trends:
    env_file:
      - .env
    image: trends:${VERSION}
    ports:
      - 5001:5001
    container_name: trends
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./trends/data:/app/data
