// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package history

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddData() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"grid grid-cols-12\"><form id=\"data-form\" class=\"mb-8\"><h2 class=\"font-bold mb-2\">Add New Row</h2><div class=\"mb-4 text-center\"><label for=\"name\" class=\"block text-sm font-medium text-gray-700\">CP</label> <input type=\"text\" id=\"name\" name=\"name\" class=\"mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm\"></div><div class=\"mb-4 text-center\"><label for=\"age\" class=\"block text-sm font-medium text-gray-700\">HP</label> <input type=\"number\" id=\"age\" name=\"age\" class=\"mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm\"></div><div class=\"mb-4 text-center\"><label for=\"city\" class=\"block text-sm font-medium text-gray-700\">LP</label> <input type=\"text\" id=\"city\" name=\"city\" class=\"mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 &gt;sm:text-sm\"></div><div class=\"mb-4 text-center\"><label for=\"city\" class=\"block text-sm font-medium text-gray-700\">Date</label> <input type=\"text\" id=\"city\" name=\"city\" class=\"mt-1 block w-full px-3 py-2 bg-white border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 &gt;sm:text-sm\"></div><button type=\"submit\" class=\"mb-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">Add Data</button></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
